trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: flake8
  displayName: Flake8 test

- script: |
    pip install pytest pytest-cov
    pip install https://github.com/RobertoPrevato/pytest-azurepipelines/archive/css_styles.zip
    python -m pytest tests/ --cov roconfiguration --cov-report html
  displayName: Run pytest tests

- script: |
    pip install --upgrade twine setuptools wheel
    python setup.py sdist bdist_wheel
  displayName: 'create artifacts'
  condition: and(succeeded(), eq(variables['python.version'], '3.8'))

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: dist
    artifactName: 'dist_$(python.version)'
  displayName: 'publish artifacts'
  condition: and(succeeded(), eq(variables['python.version'], '3.8'))
